### ISSUE TITLE
Support piped stdin

### ISSUE THREAD

**Issue by mardukbp** [whitfin/runiq#10]
It is very common to pipe the output of `cat` or `find` to a filtering program. It would be great if `runiq` could be used as a cross-platform drop-in replacement for `uniq`.

**Comment by whitfin** [comment]
This is already possible if you use `-` as the input source, which is modeled after tools like `cat`.

**Comment by mardukbp** [comment]
Just discovered that reading the code. It would be good to mention it in the help.
