### ISSUE TITLE
runiq as a library?

### ISSUE THREAD

**Issue by Uinelj** [whitfin/runiq#16]
Hi,

I've been using as a library to be able to provide multiple filter implementations depending on context,  and while forking the reposity I noticed the following lines in the `main.rs` file:
```rs
//! Runiq is only built as a command line tool, although it may be
//! distributed as a core crate if the backing implementation becomes
//! interesting for other use cases.
```

While I'm currently happy with [my solution](https://github.com/Uinelj/runiq/commit/61681f2a1230abc00e464a3a5b381b5d51f16a3d), I wonder if it would benefit people to integrate changes in the project so that `runiq` could be used both as a deduplication tool and library.

**Comment by runiq** [comment]
This may sound weird coming from me, but… yeah, I'd also like this.

**Comment by Uinelj** [comment]
The repository seems to be stale, and the author has not responded to issues for a long time 😢 

I uploaded my fork (only adding lib access support) on crates.io, using the name [runiq-lib](https://crates.io/crates/runiq-lib). I do not (currently) plan on improving anything besides enabling lib access, though.

**Comment by whitfin** [comment]
I wouldn't call it stale, more that there's nothing time sensitive that needs doing.

What are the use cases where you would use this as a library, and what sort of interface would you expect?

**Comment by Uinelj** [comment]
Yep, stale was not the best choice of words, I apologize!

My use case is pretty simple: I use the Filter trait and its implementations to deduplicate data. I've been looking for high performance implementations. Using runiq as a library makes it easy to integrate high performance implementations while enabling the API user to define its own filters in a compatible manner.

**Comment by whitfin** [comment]
Hi @Uinelj + @runiq!

I know this is waaaaay late, but I finally got some time to put some love back into this repository and just wanted to let you know that as of v2.0.0 you will be able to use the `Filter` trait and all implementations directly as a library.

Sorry for taking so long, but hopefully better late than never?

**Comment by runiq** [comment]
My name is @runiq and I approve of this release :tada:
